apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-game
  namespace: my-gamens
  labels:
    app: my-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-game
  template:
    metadata:
      labels:
        app: my-game
    spec:
      containers:
      - name: my-game-container
        image: yasirzia/my-webserver:latest
        ports:
        - containerPort: 80
